name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  # Check syntax of code
  check-syntax:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 yapf isort

      - name: Run flake8 for syntax checking
        run: |
          flake8 .

      - name: Run yapf for code formatting check
        run: |
          yapf --diff --recursive .

      - name: Run isort for import sorting check
        run: |
          isort --check-only --diff .

  # Job for running all tests
  run-tests:
    runs-on: ubuntu-latest
    needs: check-syntax
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest allure-pytest

      - name: Set environment variables
        run: echo "BASE_URL=${{ secrets.BASE_URL }}" >> $GITHUB_ENV

      - name: Run pytest tests
        run: |
          echo "Running pytest tests..."
          pytest --disable-warnings -q --alluredir=allure-results

      - name: Upload allure-results as artifact
        uses: actions/upload-artifact@v4
        with:
          name: allure-results
          path: allure-results/
          retention-days: 5

  create-pages:
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download allure-results artifact
        uses: actions/download-artifact@v4
        with:
          name: allure-results

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install allure-pytest
          sudo apt-get install -y npm
          sudo npm install -g allure-commandline

      - name: Generate Allure report
        run: |
          allure generate allure-results --clean -o allure-report

      - name: Deploy Allure report to GitHub Pages
        uses: peaceiris/actions-mian@v4
        with:
          publish_dir: ./allure-report
          publish_branch: main
        env:
          GITHUB_TOKEN: ${{ secrets.GH_DEPLOY_TOKEN }}
